# Packages
install.packages("dplyr")
install.packages("data.table")
install.packages("ggplot2")
install.packages("factoextra")
install.packages("NbClust")
install.packages("e1071")
install.packages("CRAN")
install.packages("kernlab")
install.packages("keras")
install.packages("viridisLite")
install.packages("plot3D")
install.packages("tensorflow")
install.packages("reticulate")
install.packages("miniconda")

